# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 539c54d35a65596be65bc76296c8f764e55910c9c201656c9ac6e761d6cc5bfb45ccb2b88c39fa1a2bb4756a4b4fef2aefe2ba67207c93c4a377fd5c2a9be4b6

test:
  secret_key_base: 7c2f7871fbe07ad8f76424143fe0ac02bbd1e48906e6ea286ab8a037e0957c690d4c49c842c2f9530e64eb9832fecfa38d646f169883350008d30a4089432756

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
